server:
  port: 8534
twilio:
  accountSid: your account ssid
  authToken: auth toke
  phoneNumber: your mobile number 
image:
  upload-dir: /images
spring:
  datasource:
    url: jdbc:postgresql://AAKASH:5432/OMFED
    username: postgres
    password: Akash@Sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
