server:
  port: 8534
twilio:
  accountSid: ACb4498e0806b69ff5c7b346d0e52b5042
  authToken: e21eed016c1fdd2a36ee63490d66ae04
  phoneNumber: +91 9938337734 
image:
  upload-dir: /images
spring:
  datasource:
    url: jdbc:postgresql://AAKASH:5432/OMFED
    username: postgres
    password: Akash@Sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect